name: Continuous Integration

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Run tests
        run: vendor/bin/pest

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build executable
        run: php igit app:build --build-version ${{ steps.vars.outputs.sha_short }}

      - name: Verify executable
        run: php builds/igit

      - name: Verify executable version
        run: php builds/igit --version

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: igit
          path: builds/igit


  release:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          ref: releases

      - name: Remove old build
        run: rm -rf builds/igit

      - name: Download executable artifact
        uses: actions/download-artifact@v3
        with:
          name: igit
          path: builds

      - name: Debug artifact
        run: |
          ls -la builds
          ls builds/igit
          stat builds/igit
        

      - name: Commit build
        uses: EndBug/add-and-commit@v9
        with:
          message: "Build executable for commit ${{ github.sha }}"
          add: "builds/igit --force"
          committer_name: "GitHub Actions"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create a release
        uses: ncipollo/release-action@v1
        if: false # Disabled for now
        with:
          artifacts: builds/igit
          # commit: ${{ github.sha }}
          commit: releases
          tag: dev-${{ github.sha }}
          name: Development Release ${{ github.sha }}
          body: |
            **This is a development release for commit ${{ github.sha }}.**
            
            It is not intended for production use and may contain bugs or incomplete features.
          prerelease: true
          skipIfReleaseExists: true

